### ISSUE TITLE
Hardcode `ForeGround=1` in acng.sh?

### ISSUE THREAD

**Issue by TobiX** [konstruktoid/container-aptcacherng-build#39]
Just a suggestion: Maybe hardcode the `ForeGround=1` option in the `acng.sh` entrypoint script? There is probably never a case where I want to run the container without this option (since the container would die immediately if acng forks into the background).

This would remove one possible footgun when somebody wants to customize the container.

**Comment by konstruktoid** [comment]
yeah, good idea. will fix.

**Comment by konstruktoid** [comment]
should be fixed with https://github.com/konstruktoid/container-aptcacherng-build/pull/40

**Comment by TobiX** [comment]
Can confirm that the container now runs with custom options without specifying `ForeGround=1` :+1:
